### ISSUE TITLE
Check mentions less often (rate limit)

### ISSUE THREAD

**Issue by bmarwell** [bmarwell/twitter-metricbot#101]
```
twittermetricbot | [2023-06-25T10:52:45.938] [ERROR] i.g.b.t.m.w.t.MentionEventHandler - Problem executing [MENTIONS_TIMELINE].
twittermetricbot | java.lang.IllegalStateException: 429:Returned in API v1.1 when a request cannot be served due to the application's rate limit having been exhausted for the resource. See Rate Limiting in API v1.1.(https://dev.twitter.com/docs/rate-limiting/1.1)
twittermetricbot | message - Rate limit exceeded
twittermetricbot | code - 88
twittermetricbot | 
twittermetricbot | Relevant discussions can be found on the Internet at:
twittermetricbot |      http://www.google.co.jp/search?q=7e678613 or
twittermetricbot |      http://www.google.co.jp/search?q=d050ba17
twittermetricbot | TwitterException{exceptionCode=[7e678613-d050ba17], statusCode=429, message=Rate limit exceeded, code=88, retryAfter=-1, rateLimitStatus=RateLimitStatusJSONImpl{remaining=0, limit=75, resetTimeInSeconds=1687690369, secondsUntilReset=3}, version=4.0.7}
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.MentionEventHandler.onException(MentionEventHandler.java:85)
twittermetricbot |      at twitter4j.AsyncTwitterImpl$AsyncTask.run(AsyncTwitterImpl.java:2978)
twittermetricbot |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
twittermetricbot |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
twittermetricbot |      at java.base/java.lang.Thread.run(Unknown Source)
twittermetricbot | Caused by: twitter4j.TwitterException: 429:Returned in API v1.1 when a request cannot be served due to the application's rate limit having been exhausted for the resource. See Rate Limiting in API v1.1.(https://dev.twitter.com/docs/rate-limiting/1.1)
twittermetricbot | message - Rate limit exceeded
twittermetricbot | code - 88
twittermetricbot | 
twittermetricbot |      at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
twittermetricbot |      at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
twittermetricbot |      at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
twittermetricbot |      at twitter4j.TwitterImpl.get(TwitterImpl.java:2066)
twittermetricbot |      at twitter4j.TwitterImpl.getMentionsTimeline(TwitterImpl.java:114)
twittermetricbot |      at twitter4j.AsyncTwitterImpl$1.invoke(AsyncTwitterImpl.java:66)
twittermetricbot |      at twitter4j.AsyncTwitterImpl$AsyncTask.run(AsyncTwitterImpl.java:2973)
twittermetricbot |      ... 3 common frames omitted
```

**Comment by bmarwell** [comment]
old app was still running
