### ISSUE TITLE
Duplicate status if units are in source tweet itself

### ISSUE THREAD

**Issue by bmarwell** [bmarwell/twitter-metricbot#102]
```
twittermetricbot | [2023-06-25T10:55:27.713] [INFO ] i.g.b.t.m.w.l.TweetMentionListener - Emitting event for tweet: [1672921352339087360]/[Test: @metricbot1 please what is 1oz ?].
twittermetricbot | [2023-06-25T10:55:28.101] [INFO ] i.g.b.t.m.web.twitter.TweetResponder - Checking response to event [io.github.bmarwell.twitter.metricbot.web.events.TweetProcessRequest@db0b3816].
twittermetricbot | [2023-06-25T10:55:28.127] [INFO ] i.g.b.t.m.web.twitter.TweetResponder - Tweet itself contains units.
twittermetricbot | [2023-06-25T10:55:28.163] [INFO ] i.g.b.t.m.web.twitter.TweetResponder - Sending status response to [1672921352339087360]: [@bmarwell
twittermetricbot | For your convenience, the metric units:
twittermetricbot | 1.0oz=28.3g].
twittermetricbot | [2023-06-25T10:55:28.329] [ERROR] i.g.b.t.m.web.twitter.TweetResponder - Unable to send reply: [StatusUpdate{status='@bmarwell
twittermetricbot | For your convenience, the metric units:
twittermetricbot | 1.0oz=28.3g', inReplyToStatusId=1672921352339087360, location=null, placeId='null', displayCoordinates=true, possiblySensitive=false, mediaName='null', mediaBody=null, mediaFile=null, mediaIds=null, autoPopulateReplyMetadata=false, attachmentUrl='null'}].
twittermetricbot | twitter4j.TwitterException: 403:The request is understood, but it has been refused. An accompanying error message will explain why. This code is used when requests are being denied due to update limits (https://support.twitter.com/articles/15364-about-twitter-limits-update-api-dm-and-following).
twittermetricbot | message - Status is a duplicate.
twittermetricbot | code - 187
twittermetricbot | 
twittermetricbot |      at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:170)
twittermetricbot |      at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
twittermetricbot |      at twitter4j.HttpClientBase.post(HttpClientBase.java:86)
twittermetricbot |      at twitter4j.TwitterImpl.post(TwitterImpl.java:2120)
twittermetricbot |      at twitter4j.TwitterImpl.updateStatus(TwitterImpl.java:236)
twittermetricbot |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
twittermetricbot |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
twittermetricbot |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
twittermetricbot |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
twittermetricbot |      at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
twittermetricbot |      at [internal classes]
twittermetricbot |      at twitter4j.Twitter$TwitterBase$DirectMessagesResources$FavoritesResources$FriendsFollowersResources$HelpResources$ListsResources$PlacesGeoResources$SavedSearchesResources$SearchResource$SpamReportingResource$SuggestedUsersResources$TimelinesResources$TrendsResources$TweetsResources$UsersResources$OAuth2Support$OAuthSupport$Serializable$1449523991$Proxy$_$$_WeldClientProxy.updateStatus(Unknown Source)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder.doRespondTwoPotentallyBoth(TweetResponder.java:142)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder$Proxy$_$$_WeldSubclass.doRespondTwoPotentallyBoth(Unknown Source)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder.doRespond(TweetResponder.java:124)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder$Proxy$_$$_WeldSubclass.doRespond(Unknown Source)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder.tryRespond(TweetResponder.java:91)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder$Proxy$_$$_WeldSubclass.tryRespond(Unknown Source)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder.onTweetFound(TweetResponder.java:62)
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.twitter.TweetResponder$Proxy$_$$_WeldSubclass.onTweetFound(Unknown Source)
twittermetricbot |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
twittermetricbot |      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
twittermetricbot |      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
twittermetricbot |      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
twittermetricbot |      at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
twittermetricbot |      at [internal classes]
twittermetricbot |      at io.github.bmarwell.twitter.metricbot.web.listener.TweetResponseListener.emitMention(TweetResponseListener.java:68)
twittermetricbot |      at com.ibm.ws.concurrent.internal.ScheduledTask.call(ScheduledTask.java:422)
twittermetricbot |      at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
twittermetricbot |      at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:247)
twittermetricbot |      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
twittermetricbot |      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
twittermetricbot |      at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by bmarwell** [comment]
old app was still running
